<a href="https://colab.research.google.com/github/mkbahk/PandasLearning/blob/main/_Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기




---



#Pandas란?
관계 또는 레이블링 데이터로 쉽게 직관적으로 작업할 수 있도록 고안된 빠르고, 유연하며 표현력이 뛰어난 데이터 구조를 제공하는 Python 패키지

# Pandas의 특징
* 부동 소수점이 아닌 데이타뿐만 아니라 부동 소수점 데이터에서도 결측 데이터(NaN으로 표시됨)를 쉽게 처리
* 크기 변이성(Size mutability): DataFrame 및 고차원 객체에서 열을 삽입 및 삭제가능
* 자동 및 명시적(explicit) 데이터 정렬: 객체를 라벨 집합에 명시적으로 정렬하거나, 사용자가 라벨을 무시하고 Series, DataFrame등의 계산에서 자동적으로 데이타 조정 가능
* 데이타 세트에서 집계 및 변환을 위한 분할(split), 적용(apply), 결합(combine)작업을 수행할 수 있는 강력하고 유연한 group-by 함수 제공
* 누락된 데이타 또는 다른 Python 및 Numpy 데이타 구조에서 서로 다른 인텍싱 데이터를 DataFrame개체로 쉽게 변환
* 대용량 데이타 세트의 지능형 라벨기반 슬라이싱, 고급 인텍싱 및 부분 집합 구하기 가능
* 직관적인 데이타 세트 병합 및 결함
* 데이타 세트의 유연한 재구성 및 피벗
* 축의 계층적 라벨링(눈금당 여러 개의 라벨을 가질 수 있음)
* 플렛 파일(CSV 및 구분), Excel파일, 데이타베이스 로딩 및 초고속 HDF5 형식의 데이타저장/로드에 사용되는 강력한 IO도구
* 시계열 특정 기능: 날짜 범위 생성 및 주파수 변환, 무빙 윈도우(Moving window) 통계, 날짜 이동 및 지연

In [2]:
import numpy as np
import pandas as pd #pandas는 numpy 기반으로 작성됨, 그래서 먼저 numpy loading필요
print(np.__version__)
print(pd.__version__)

1.19.5
1.1.5


## Pandas 객체


### Series 객체

In [ ]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s #index가 함께 저장된

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [ ]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s[1]

0.25

In [ ]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [ ]:
s = pd.Series([0.0, 0.25, 0.5, 0.75, 1.0],
              index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
s['c']

0.5

In [ ]:
s[['c', 'd', 'e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [ ]:
'b' in s

True

In [ ]:
s = pd.Series([0.0, 0.25, 0.5, 0.75, 1.0],
              index=[2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [ ]:
s[4]

0.25

In [ ]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [ ]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
s.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [ ]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [ ]:
pop_tuple ={"서울특별시": 9720645,
            "부산광역시": 3404423,
            "대구광역시": 2427954,
            "인천광역시": 2947217,
            "대전광역시": 1471040,
            "광주광역시": 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720645
부산광역시    3404423
대구광역시    2427954
인천광역시    2947217
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [ ]:
population['서울특별시']

9720645

In [ ]:
population['서울특별시':'인천광역시'] #슬라이싱

서울특별시    9720645
부산광역시    3404423
대구광역시    2427954
인천광역시    2947217
dtype: int64

### DataFrame 객체
* 여러 컬럼이 들어간 객체형태로 만드는 것이 가능

In [ ]:
pd.DataFrame([{'A':2, 'B':4, 'D':3}, 
              {'A':4, 'B':5, 'C':7}]) #2차원형태로, Missing Valule 처리가 뛰어남

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [ ]:
pd.DataFrame(np.random.rand(5, 5),  #randint 아님 
             columns=['A', 'B', 'C', 'D', 'E'],
             index=[1, 2, 3, 4, 5]) 


A         B         C         D         E
1  0.185313  0.763309  0.308573  0.684818  0.070459
2  0.280880  0.484197  0.573261  0.570421  0.425205
3  0.834974  0.345010  0.159011  0.727585  0.692102
4  0.136138  0.992849  0.948944  0.655484  0.654082
5  0.103116  0.536371  0.176305  0.349696  0.081829

In [ ]:
male_tuple = {"서울특별시": 4732275,
            "부산광역시": 1668618,
            "대구광역시": 1476813,
            "인천광역시": 1198815,
            "대전광역시": 734441,
            "광주광역시": 720060}

male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
대구광역시    1476813
인천광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [ ]:
female_tuple = {"서울특별시": 4988571,
            "부산광역시": 1735805,
            "대구광역시": 1470404,
            "인천광역시": 1229139,
            "대전광역시": 736599,
            "광주광역시": 734988}

female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
대구광역시    1470404
인천광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [ ]:
korea_df = pd.DataFrame({'전체인구수': population,
                        '남자인구수': male,
                        '여자인구수': female})  # RDB Join 기능이 아주 쉽게 완성됨
korea_df

전체인구수    남자인구수    여자인구수
서울특별시  9720645  4732275  4988571
부산광역시  3404423  1668618  1735805
대구광역시  2427954  1476813  1470404
인천광역시  2947217  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [ ]:
korea_df.index

Index(['서울특별시', '부산광역시', '대구광역시', '인천광역시', '대전광역시', '광주광역시'], dtype='object')

In [ ]:
korea_df.columns

Index(['전체인구수', '남자인구수', '여자인구수'], dtype='object')

In [ ]:
korea_df['여자인구수'] #RDB Select

서울특별시    4988571
부산광역시    1735805
대구광역시    1470404
인천광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [ ]:
korea_df['서울특별시':'인천광역시'] #슬라이스 == RDB Select

전체인구수    남자인구수    여자인구수
서울특별시  9720645  4732275  4988571
부산광역시  3404423  1668618  1735805
대구광역시  2427954  1476813  1470404
인천광역시  2947217  1198815  1229139

### Index 객체

|클래스|설명|
|---|---|
|Index| 일반적인 Index 객체이며, NumPy배열 형식으로 축의 이름 표현|
|Int64Index|정수 값을 위한 Index|
|MultiIndex|단일 축에 여러 단계 색인을 표현하는 계층적 Index객체(튜플의 배열과 유사|
|DatetimeIndex| NumPy의 datetime64 타입으로 타임스템프 저장|
|PeriodIndex| 기간 데이타를 위한 Index|



In [ ]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [ ]:
idx[1]

4

In [ ]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [ ]:
idx[-1::]

Int64Index([10], dtype='int64')

In [ ]:
idx[::2] #step을 띄움

Int64Index([2, 6, 10], dtype='int64')

In [ ]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산
|연산자|메소드|설명|
|---|---|---|
||```append```|색인 객체를 추가해 새로운 색인 반환|
||```difference```|색인의 차집합 반환|
|```&```|```intersection```|색인의 교집합 반환|
|```\|```|```union```|색인의 합집합 반환|
| |```isin```|색인이 존재하는지 여부를 불리언 배열로 반환|
| |```delete```|색인이 삭제된 새로운 색인 반환|
| |```drop```|값이 삭제된 새로운 색인 반환|
| |```insert```|색인이 추가된 새로운 색인반환|
| |```is_monotonic```|색인이 단조성을 가지면 True|
| |```is_unique```|중복되는 색인이 없다면 True|
| |```unique```|색인에서 중복되는 요소를 제거하고 유일한 값만 반환|
|```^```|``` ```|여집합, 공통적인 것을 뺀 나머지|



In [ ]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])
print(idx1.append(idx2))
print(idx1 + idx2)

print(idx1.difference(idx2)) #idx2에 없는 것만 
print(idx1 - idx2)

print(idx1.intersection(idx2)) #공통되는 부분만
print(idx1 & idx2)

print(idx1.union(idx2)) #합집합인데 중복을 제거함
print(idx1 | idx2)

print(idx1.delete(0)) #첫번째 1값이 빠짐
print(idx1)
print(idx1.drop(1))
print(idx1)

print(idx1 ^ idx2) #여집합, 공통적인 것을 뺀 나머지

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([3, 6, 9, 12, 15], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')




---



## 인덱싱(Indexing)

In [ ]:
s = pd.Series([0.0, 0.25, 0.5, 0.75, 1.0],
              index=['a', 'b', 'c', 'd', 'e'])
print(s)


a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64


In [ ]:
print(s['b'])

0.25


In [ ]:
print('b' in s)

True


In [ ]:
print(s.keys())

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [ ]:
print(s.items()) #묶여서 있어서
print(list(s.items())) #list로 한번 감싸주어야 함

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]


In [ ]:
s['f'] = 1.25 #값을 추가할 수 있다.
print(s)

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64


In [ ]:
print(s['a': 'd'])
print(s[0:4]) #숫자로 슬라이싱 가능

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64
a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64


In [ ]:
s[(s > 0.4) & (s < 0.8)] #위 조건에 해당하는 것만 출력

c    0.50
d    0.75
dtype: float64

In [ ]:
s[['a', 'c', 'e']] #원하는 값만 부분부분 출력하는 것도 가능

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [ ]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
              index=[1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [ ]:
s[1]

'a'

In [ ]:
s[2:4]

5    c
7    d
dtype: object

In [ ]:
s.iloc[1] #int location

'b'

In [ ]:
s.iloc[0]

'a'

In [ ]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [ ]:
s.reindex(range(10)) #0~9까지의 index로 바꿔주라

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [ ]:
s.reindex(range(10), method='bfill') #빈값은 바로 전의 값으로 붙여주라.

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱
|사용방법|설명|
|---|---|
|df[val]|하나의 컬럼 또는 여러 컬럼을 선택|
|df.loc[val]|라벨값으로 로우의 부분집합 선택|
|df.loc[:, val]|라벨값으로 컬럼의 부분집합 선택|
|df.loc[val1, val2]|라벨값으로 로우와 컬럼의 부분집합 선택|
|df.iloc[where]|정수 색인으로 로우의 부분집합 선택|
|df.iloc[:, where]|정수 색인으로 컬럼의 부분집합 선택|
|df.at[label_i, label_j]|로우와 컬럼의 라벨로 단일 값 선택|
|df.iat[i, j]|로우와 컬럼의 정수 색인으로 단일 값 선택|
|reindex|하나 이상의 축을 새로운 색인으로 재-색인|
|get_value, set_value|로우와 컬럼의 이름으로 값 선택|



In [ ]:
korea_df

전체인구수    남자인구수    여자인구수
서울특별시  9720645  4732275  4988571
부산광역시  3404423  1668618  1735805
대구광역시  2427954  1476813  1470404
인천광역시  2947217  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [ ]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
대구광역시    1476813
인천광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [ ]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
대구광역시    1476813
인천광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [ ]:
# korea_df."남자인구수"

In [ ]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
대구광역시    1470404
인천광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [ ]:
korea_df['남여비율'] = (korea_df['남자인구수'] / korea_df['여자인구수']) * 100

In [ ]:
korea_df

전체인구수    남자인구수    여자인구수        남여비율
서울특별시  9720645  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
대구광역시  2427954  1476813  1470404  100.435867
인천광역시  2947217  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [ ]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
대구광역시    100.435867
인천광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [ ]:
korea_df.values #배열형태로 보여 줌

array([[9.72064500e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.42795400e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.94721700e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [ ]:
korea_df.T

서울특별시         부산광역시  ...         대전광역시         광주광역시
전체인구수  9.720645e+06  3.404423e+06  ...  1.471040e+06  1.455048e+06
남자인구수  4.732275e+06  1.668618e+06  ...  7.344410e+05  7.200600e+05
여자인구수  4.988571e+06  1.735805e+06  ...  7.365990e+05  7.349880e+05
남여비율   9.486234e+01  9.612935e+01  ...  9.970703e+01  9.796895e+01

[4 rows x 6 columns]

In [ ]:
korea_df.values[0]

array([9.72064500e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [ ]:
korea_df.values[0,0]

9720645.0

In [ ]:
korea_df.values[5,2]

734988.0

In [ ]:
korea_df['전체인구수']

서울특별시    9720645
부산광역시    3404423
대구광역시    2427954
인천광역시    2947217
대전광역시    1471040
광주광역시    1455048
Name: 전체인구수, dtype: int64

In [ ]:
korea_df.loc[:'인천광역시', :"남자인구수"]

전체인구수    남자인구수
서울특별시  9720645  4732275
부산광역시  3404423  1668618
대구광역시  2427954  1476813
인천광역시  2947217  1198815

In [ ]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

전체인구수    남자인구수    여자인구수        남여비율
서울특별시  9720645  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
대구광역시  2427954  1476813  1470404  100.435867
인천광역시  2947217  1198815  1229139   97.532907

In [ ]:
korea_df.loc[(korea_df.전체인구수 < 2000000)]

전체인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [ ]:
korea_df.loc[(korea_df.전체인구수 > 2500000)]

전체인구수    남자인구수    여자인구수       남여비율
서울특별시  9720645  4732275  4988571  94.862336
부산광역시  3404423  1668618  1735805  96.129346
인천광역시  2947217  1198815  1229139  97.532907

In [ ]:
korea_df.loc[korea_df.남여비율 > 100]

전체인구수    남자인구수    여자인구수        남여비율
대구광역시  2427954  1476813  1470404  100.435867

In [ ]:
korea_df.loc[(korea_df.전체인구수 > 2500000) & (korea_df.남여비율 > 90)]

전체인구수    남자인구수    여자인구수       남여비율
서울특별시  9720645  4732275  4988571  94.862336
부산광역시  3404423  1668618  1735805  96.129346
인천광역시  2947217  1198815  1229139  97.532907

In [ ]:
korea_df.iloc[:3, :2] #3행, 2열

전체인구수    남자인구수
서울특별시  9720645  4732275
부산광역시  3404423  1668618
대구광역시  2427954  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [ ]:
korea_df

전체인구수    남자인구수    여자인구수        남여비율
서울특별시  9720645  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
대구광역시  2427954  1476813  1470404  100.435867
인천광역시  2947217  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [ ]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
              ('부산광역시', 2010), ('부산광역시', 2020),
              ('인천광역시', 2010), ('인천광역시', 2020),
              ('대구광역시', 2010), ('대구광역시', 2020),
              ('대전광역시', 2010), ('대전광역시', 2020),
              ('광주광역시', 2010), ('광주광역시', 2020)]

In [ ]:
idx_tuples #이것은 multiindexing이 아니고 중복된 값을 가지고 있는 형태임

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [ ]:
pop_tuples = [10312545, 9720846,
             2567910, 3404423,
             2758296, 2947217,
             2511676, 2427954,
             1503664, 1471040,
             1454636, 1455048]
            

In [ ]:
population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [ ]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [ ]:
population = population.reindex(midx)
population #멀티인덱싱이 만들어 져 있는 형태, 중복된 것이 아니라 서울특벽시 밑에 2010과 2020이 있는 형태임

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population[:, 2010] #2010년까지만 보여줘

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [ ]:
population['대전광역시', :] #대전광역시 인것 다 보여줘

2010    1503664
2020    1471040
dtype: int64

In [ ]:
korea_mdf = population.unstack() #전형적인 data frame구조로 바꿈
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2947217

In [ ]:
korea_mdf.stack() #다중인덱싱 스텍으로 변환, 그러나 아래의 결과는 변환되지 않았음. 버그인가?

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [ ]:
male_tuples = [5111259, 4732275,
              1773170, 1668618,
              1390356, 1476813,
              1255245, 1198815,
              753648, 734441,
              721780, 720060]
male_tuples           

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [ ]:
female_tuples = [5201285, 4988571,
              1794740, 1735805,
              1367940, 1470404,
              1256431, 1229139,
              750016, 736599,
              732856, 734988]
female_tuples           

[5201285,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201285
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [ ]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269158
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [ ]:
ratio.unstack()

2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269158   94.862336
인천광역시  101.638668  100.435867

In [ ]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples,
                          '남여비율': ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201285   98.269158
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [ ]:
df =  pd.DataFrame(np.random.rand(6, 3),
                   index=[['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]],
                   columns=['c1', 'c2', 'c3'])
df

c1        c2        c3
a 1  0.862241  0.997640  0.737681
  2  0.942492  0.017202  0.857789
b 1  0.254486  0.439428  0.589048
  2  0.507148  0.722619  0.683281
c 1  0.071674  0.928934  0.384209
  2  0.812582  0.818694  0.454498

In [ ]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]]) #Multiindex 하는 방법#1

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)]) #Multiindex하는 방법#2

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex.from_product([['a', 'b', 'c'],[1, 2]]) #2개 벡터를 곱하는 결과를 Multi Index로 만들어 주라

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex(levels=[['a', 'b', 'c'],[1, 2]],
              codes=[[0, 0, 1, 1, 2, 2],[0, 1, 0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population.index.names = ['행정구역', '년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                 names=['name1', 'name2'])

cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'],[1, 2]],
                                  names=['col_name1', 'col_name2'])

data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index=idx, columns=cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1      1.07 -0.94 -0.39 -1.23 -1.06  0.21
      2      0.45 -0.44  1.09 -1.92  0.74  0.08
b     1     -1.75 -0.39  0.17 -0.73 -0.04  0.77
      2      0.12 -0.11 -0.71  0.26 -0.37  0.64
c     1     -0.07 -2.02 -0.04  1.48 -0.12  0.85
      2     -1.05  0.56  0.42  1.45 -0.23  1.62

In [ ]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1     -0.39 -1.23
      2      1.09 -1.92
b     1      0.17 -0.73
      2     -0.71  0.26
c     1     -0.04  1.48
      2      0.42  1.45

#### 인덱싱 및 슬라이싱

In [ ]:
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [ ]:
population['인천광역시', 2010]

2758296

In [ ]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [ ]:
population[population > 10000000]

행정구역   년도  
서울특별시  2010    10312545
dtype: int64

In [ ]:
population[['대구광역시', '대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [ ]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1      1.07 -0.94 -0.39 -1.23 -1.06  0.21
      2      0.45 -0.44  1.09 -1.92  0.74  0.08
b     1     -1.75 -0.39  0.17 -0.73 -0.04  0.77
      2      0.12 -0.11 -0.71  0.26 -0.37  0.64
c     1     -0.07 -2.02 -0.04  1.48 -0.12  0.85
      2     -1.05  0.56  0.42  1.45 -0.23  1.62

In [ ]:
mdf['c2', 2] #c2에 2번 column만

name1  name2
a      1       -1.23
       2       -1.92
b      1       -0.73
       2        0.26
c      1        1.48
       2        1.45
Name: (c2, 2), dtype: float64

In [ ]:
mdf.iloc[:3, :4] #정수인댁싱

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1      1.07 -0.94 -0.39 -1.23
      2      0.45 -0.44  1.09 -1.92
b     1     -1.75 -0.39  0.17 -0.73

In [ ]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1       -0.39
       2        1.09
b      1        0.17
       2       -0.71
c      1       -0.04
       2        0.42
Name: (c2, 1), dtype: float64

In [ ]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2     -0.44 -1.92  0.08
b     2     -0.11  0.26  0.64
c     2      0.56  1.45  1.62

#### 다중 인덱스 재정렬

In [ ]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [ ]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201285   98.269158
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [ ]:
#korea_mdf['서울특별시':'인천광역시'] # UnsortedIndexError  발생, 슬라이스의 결과를 보여줄려면 정렬이 되어있어야 한다. 정렬이 않되어 있어 발생하는 에러

korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201285   98.269158
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
korea_mdf['서울특별시':'인천광역시'] 

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201285   98.269158
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
korea_mdf.unstack(level=0)

총인구수                    ...       남여비율                       
행정구역    광주광역시    대구광역시    대전광역시  ...      부산광역시      서울특별시       인천광역시
년도                               ...                                  
2010  1454636  2511676  1503664  ...  98.798155  98.269158  101.638668
2020  1455048  2427954  1471040  ...  96.129346  94.862336  100.435867

[2 rows x 24 columns]

In [ ]:
korea_mdf.unstack(level=1)

총인구수             남자인구수  ...    여자인구수        남여비율            
년도         2010     2020     2010  ...     2020        2010        2020
행정구역                               ...                                 
광주광역시   1454636  1455048   721780  ...   734988   98.488653   97.968946
대구광역시   2511676  2427954  1255245  ...  1229139   99.905606   97.532907
대전광역시   1503664  1471040   753648  ...   736599  100.484256   99.707032
부산광역시   2567910  3404423  1773170  ...  1735805   98.798155   96.129346
서울특별시  10312545  9720846  5111259  ...  4988571   98.269158   94.862336
인천광역시   2758296  2947217  1390356  ...  1470404  101.638668  100.435867

[6 rows x 8 columns]

In [ ]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
 

In [ ]:
korea_mdf

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201285   98.269158
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남여비율
년도                                                 
2010  광주광역시   1454636   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201285   98.269158
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat = korea_mdf.reset_index(level=(0, 1))
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454636   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201285   98.269158
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [ ]:
idx_flat.set_index(['행정구역', '년도'])

총인구수    남자인구수    여자인구수        남여비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201285   98.269158
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [ ]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    5
1    3
2    8
3    0
4    1
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                  columns=['A', 'B', 'C'])
df

A  B  C
0  3  6  2
1  2  4  9
2  7  7  0

In [ ]:
np.exp(s)

0     148.413159
1      20.085537
2    2980.957987
3       1.000000
4       2.718282
dtype: float64

In [ ]:
np.cos(df * np.pi / 4)

A             B             C
0 -7.071068e-01 -1.836970e-16  6.123234e-17
1  6.123234e-17 -1.000000e+00  7.071068e-01
2  7.071068e-01  7.071068e-01  1.000000e+00

In [ ]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1, 2, 3, 4, 5])
s1 + s2 #결과적으로 같은 index끼리만 덧셈연산

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [ ]:
s1.add(s2, fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                   columns=list('ACD'))
df1

A  C   D
0   4  1   9
1  17  6  10
2  19  9  13

In [ ]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                   columns = list('BAECD'))
df2

B   A   E   C   D
0   7  12  11  18   1
1   7   6   4  10  10
2  13  13  14   9  13
3   4  10  17   0   3
4  13  14  18   7  13

In [ ]:
df1 + df2

A   B     C     D   E
0  16.0 NaN  19.0  10.0 NaN
1  23.0 NaN  16.0  20.0 NaN
2  32.0 NaN  18.0  26.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [ ]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

A          B          C          D          E
0  16.000000  16.777778  19.000000  10.000000  20.777778
1  23.000000  16.777778  16.000000  20.000000  13.777778
2  32.000000  22.777778  18.000000  26.000000  23.777778
3  19.777778  13.777778   9.777778  12.777778  26.777778
4  23.777778  22.777778  16.777778  22.777778  27.777778

### 연산자 범용 함수
|Python 연산자| pandas 메소드|
|---|---|
|```+```| add, radd|
|```-```| sub, rsub, subtract|
|```*```| mul, rmul, multiply|
|```/```| truediv, div, rdiv, divide|
|```//```| floordiv, rfloordiv|
|```%```| mod|
|```**```| pow, rpow|



#### add()

In [ ]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[7, 8, 9],
       [4, 1, 7],
       [1, 1, 5]])

In [ ]:
a + a[0] #broadcasting한 후 연산

array([[14, 16, 18],
       [11,  9, 16],
       [ 8,  9, 14]])

In [ ]:
df = pd.DataFrame(a, columns=list('ABC'))
df

A  B  C
0  7  8  9
1  4  1  7
2  1  1  5

In [ ]:
df + df.iloc[0]


A   B   C
0  14  16  18
1  11   9  16
2   8   9  14

In [ ]:
df.add(df.iloc[0]) #전반적으로 NumPy에서 사용하는 연산자와 동일한 방식으로 동작함, 기본적으로 pandas가 numpy 기반으로 만들어 졌기 때문에 같은 연산자로 사용이 가능함

A   B   C
0  14  16  18
1  11   9  16
2   8   9  14

#### sub() / subtract()

In [ ]:
a

array([[7, 8, 9],
       [4, 1, 7],
       [1, 1, 5]])

In [ ]:
a - a[0] #broadcasting 한후 처리함

array([[ 0,  0,  0],
       [-3, -7, -2],
       [-6, -7, -4]])

In [ ]:
df

A  B  C
0  7  8  9
1  4  1  7
2  1  1  5

In [ ]:
df - df.iloc[0]

A  B  C
0  0  0  0
1 -3 -7 -2
2 -6 -7 -4

In [ ]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1 -3 -7 -2
2 -6 -7 -4

In [ ]:
df.subtract(df['B'], axis=0) #2차원이기 때문에 축 지정가능, 'B'열로 자기가 자기를 빼서 모두 0이 됨


A  B  C
0 -1  0  1
1  3  0  6
2  0  0  4

#### mul() / multply()




In [ ]:
a

array([[7, 8, 9],
       [4, 1, 7],
       [1, 1, 5]])

In [ ]:
a * a[1]

array([[28,  8, 63],
       [16,  1, 49],
       [ 4,  1, 35]])

In [ ]:
df

A  B  C
0  7  8  9
1  4  1  7
2  1  1  5

In [ ]:
df * df.iloc[1]

A  B   C
0  28  8  63
1  16  1  49
2   4  1  35

In [ ]:
df.mul(df.iloc[1])

A  B   C
0  28  8  63
1  16  1  49
2   4  1  35

In [ ]:
df.multiply(df.iloc[2])

A  B   C
0  7  8  45
1  4  1  35
2  1  1  25

### 나누기
#### truediv() /  div() / divide() / floordiv()

In [ ]:
a

array([[7, 8, 9],
       [4, 1, 7],
       [1, 1, 5]])

In [ ]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.57142857, 0.125     , 0.77777778],
       [0.14285714, 0.125     , 0.55555556]])

In [ ]:
df

A  B  C
0  7  8  9
1  4  1  7
2  1  1  5

In [ ]:
df / df.iloc[0]

A      B         C
0  1.000000  1.000  1.000000
1  0.571429  0.125  0.777778
2  0.142857  0.125  0.555556

In [ ]:
df.truediv(df.iloc[0])

A      B         C
0  1.000000  1.000  1.000000
1  0.571429  0.125  0.777778
2  0.142857  0.125  0.555556

In [ ]:
df.div(df.iloc[1])

A    B         C
0  1.75  8.0  1.285714
1  1.00  1.0  1.000000
2  0.25  1.0  0.714286

In [ ]:
df.divide(df.iloc[2])

A    B    C
0  7.0  8.0  1.8
1  4.0  1.0  1.4
2  1.0  1.0  1.0

In [ ]:
a // a[0] #floor_div

array([[1, 1, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  0  0  0
2  0  0  0

#### mod() : 나머지

In [ ]:
a

array([[7, 8, 9],
       [4, 1, 7],
       [1, 1, 5]])

In [ ]:
a % a[0]

array([[0, 0, 0],
       [4, 1, 7],
       [1, 1, 5]])

In [ ]:
df

A  B  C
0  7  8  9
1  4  1  7
2  1  1  5

In [ ]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  4  1  7
2  1  1  5

#### pow()

In [ ]:
a

array([[7, 8, 9],
       [4, 1, 7],
       [1, 1, 5]])

In [ ]:
a ** a[0]

array([[   823543,  16777216, 387420489],
       [    16384,         1,  40353607],
       [        1,         1,   1953125]])

In [ ]:
df

A  B  C
0  7  8  9
1  4  1  7
2  1  1  5

In [ ]:
df.pow(df.iloc[0])

A         B          C
0  823543  16777216  387420489
1   16384         1   40353607
2       1         1    1953125

In [ ]:
row = df.iloc[0, ::2] #step을 2로
row #일부만 뽑아서

A    7
C    9
Name: 0, dtype: int64

In [ ]:
df - row

A   B    C
0  0.0 NaN  0.0
1 -3.0 NaN -2.0
2 -6.0 NaN -4.0

### 정렬(Sort)

In [ ]:
s = pd.Series(range(5), index=['A', 'D', 'B', 'C', 'E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [ ]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [ ]:
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [ ]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [ ]:
df = pd.DataFrame(np.random.randint(1, 10, (4, 4)),
                  index=[2, 4, 1, 3],
                  columns=list('BDAC'))
df

B  D  A  C
2  4  6  5  7
4  1  3  7  7
1  4  4  4  2
3  5  5  6  9

In [ ]:
df.sort_index()

B  D  A  C
1  4  4  4  2
2  4  6  5  7
3  5  5  6  9
4  1  3  7  7

In [ ]:
df.sort_index(axis=1) #열 "B D A C"가 "A B C D"로 정렬딤

A  B  C  D
2  5  4  7  6
4  7  1  7  3
1  4  4  2  4
3  6  5  9  5

In [ ]:
df.sort_values(by='A') #다음 셀과 결과가 같음

B  D  A  C
1  4  4  4  2
2  4  6  5  7
3  5  5  6  9
4  1  3  7  7

In [ ]:
df.sort_values(by=['A']) #2차원이라 기준 필드를 정해주어야 함

B  D  A  C
1  4  4  4  2
2  4  6  5  7
3  5  5  6  9
4  1  3  7  7

In [ ]:
df.sort_values(by=['A', 'C']) #먼저 A를 기분으로 정렬 한 후 C를 기준으로 정렬함.

B  D  A  C
1  4  4  4  2
2  4  6  5  7
3  5  5  6  9
4  1  3  7  7

### 순위(Ranking)

|메소드|설명|
|---|---|
|```average```|기본값, 순위에 같은 값을 가지는 항목들의 평균값을 사용|
|```min```|같은 값을 가지는 그룹을 낮은 순위로 지정|
|```max```|같은 값을 가지는 구룹을 높은 순위로 지정|
|```first```|데이터 내의 위치에 따라 순위 지정|
|```dense```|같은 그룹 내에서 모두 같은 순위를 적용하지 않고 1씩 증가|




In [ ]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 5, -4, 2, 6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [ ]:
s.rank() #7번 -4를 1.0로 보고 그 위쪽으로 순위를 정함

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [ ]:
s.rank(method='first') #원래 2도 7이고, 5도 7이었는데 같은 값에도 불구하고 먼저 나온놈의 순위를 높여줌

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [ ]:
s.rank(method='max') #2에 7, 5에 7을 같은 10.0로 만들어 놓음, 위의 셀 2의 9.0이 사라지고 MAX인 5의 10.0으로 바뀜.

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

### 고성능 연산
* pandas가 대용량 DataFrame을 빠르게 연산하도록 한 기능들
* .eval() 
* .query()

In [ ]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [ ]:
%timeit df1 + df2 + df3 +df4

10 loops, best of 5: 60.1 ms per loop


In [ ]:
%timeit pd.eval('df1 + df2 + df3 + df4')

10 loops, best of 5: 40.4 ms per loop


In [ ]:
%timeit df1 * (-df2) / (-df3 * df4)

10 loops, best of 5: 90.1 ms per loop


In [ ]:
%timeit pd.eval('df1 * (-df2) / (-df3 * df4)')

10 loops, best of 5: 50.5 ms per loop


In [ ]:
%timeit (df1 < df2) & (df2 <= df3) & (df3 != df4)

10 loops, best of 5: 59.1 ms per loop


In [ ]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3) & (df3 != df4)')

10 loops, best of 5: 92.3 ms per loop


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df =  pd.DataFrame(np.random.rand(10000000, 5), columns=['A', 'B', 'C', 'D', 'E']) #100만 이상이면 메모리 터짐
df.head()

A         B         C         D         E
0  0.562275  0.091552  0.621612  0.836389  0.142864
1  0.397181  0.836181  0.822754  0.751866  0.506410
2  0.119841  0.764650  0.723250  0.625737  0.986019
3  0.237176  0.576321  0.782375  0.505033  0.811134
4  0.334402  0.971458  0.716437  0.074681  0.694662

In [ ]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

10 loops, best of 5: 140 ms per loop


In [ ]:
%timeit pd.eval('df.A + df.B / df.C - df.D * df.E')

10 loops, best of 5: 54.9 ms per loop


In [ ]:
%timeit df.eval('A + B / C - D * E') #심지어 컬럼명으로 연산도 가능함, 이것은 .eval()함수에서는 되는 것이겠지!! scan 비용때문에 약가 더 걸림

10 loops, best of 5: 89.2 ms per loop


In [ ]:
%timeit df.eval('R = A + B / C - D * E', inplace=True)
df.head()

10 loops, best of 5: 123 ms per loop


A         B         C         D         E         R
0  0.562275  0.091552  0.621612  0.836389  0.142864  0.590067
1  0.397181  0.836181  0.822754  0.751866  0.506410  1.032749
2  0.119841  0.764650  0.723250  0.625737  0.986019  0.560094
3  0.237176  0.576321  0.782375  0.505033  0.811134  0.564157
4  0.334402  0.971458  0.716437  0.074681  0.694662  1.638481

In [ ]:
%timeit df.eval('R = A - B / C + D * E', inplace=True) #계산식 반영
df.head()

10 loops, best of 5: 123 ms per loop


A         B         C         D         E         R
0  0.562275  0.091552  0.621612  0.836389  0.142864  0.534482
1  0.397181  0.836181  0.822754  0.751866  0.506410 -0.238387
2  0.119841  0.764650  0.723250  0.625737  0.986019 -0.320413
3  0.237176  0.576321  0.782375  0.505033  0.811134 -0.089805
4  0.334402  0.971458  0.716437  0.074681  0.694662 -0.969678

In [ ]:
%timeit col_mean = df.mean(1)
df['A'] + col_mean

10 loops, best of 5: 106 ms per loop


0          1.027137
1          0.909848
2          0.603021
3          0.707548
4          0.638062
             ...   
9999995    0.114882
9999996    1.507266
9999997    1.696873
9999998    1.351932
9999999    1.672179
Length: 10000000, dtype: float64

In [ ]:
%timeit df.eval('A + @col_mean')
df.head()

10 loops, best of 5: 56.7 ms per loop


A         B         C         D         E         R
0  0.562275  0.091552  0.621612  0.836389  0.142864  0.534482
1  0.397181  0.836181  0.822754  0.751866  0.506410 -0.238387
2  0.119841  0.764650  0.723250  0.625737  0.986019 -0.320413
3  0.237176  0.576321  0.782375  0.505033  0.811134 -0.089805
4  0.334402  0.971458  0.716437  0.074681  0.694662 -0.969678

In [ ]:
%timeit df[(df.A < 0.5) & (df.B < 0.4) & (df.C > 0.5)] 
df.head()

10 loops, best of 5: 138 ms per loop


A         B         C         D         E         R
0  0.562275  0.091552  0.621612  0.836389  0.142864  0.534482
1  0.397181  0.836181  0.822754  0.751866  0.506410 -0.238387
2  0.119841  0.764650  0.723250  0.625737  0.986019 -0.320413
3  0.237176  0.576321  0.782375  0.505033  0.811134 -0.089805
4  0.334402  0.971458  0.716437  0.074681  0.694662 -0.969678

In [ ]:
%timeit pd.eval('df[(df.A < 0.5) & (df.B < 0.4) & (df.C > 0.5)]')
df.head()

1 loop, best of 5: 198 ms per loop


A         B         C         D         E         R
0  0.562275  0.091552  0.621612  0.836389  0.142864  0.534482
1  0.397181  0.836181  0.822754  0.751866  0.506410 -0.238387
2  0.119841  0.764650  0.723250  0.625737  0.986019 -0.320413
3  0.237176  0.576321  0.782375  0.505033  0.811134 -0.089805
4  0.334402  0.971458  0.716437  0.074681  0.694662 -0.969678

In [ ]:
df.query('(A < 0.5) and (B < 0.4) and (C > 0.5)') #이런 방법도 있음

A         B         C         D         E         R
42       0.218688  0.031784  0.620736  0.550781  0.956345  0.694222
44       0.132547  0.043637  0.604046  0.963067  0.492702  0.534811
49       0.468706  0.036334  0.591454  0.875842  0.048950  0.450147
51       0.225828  0.015282  0.852526  0.742071  0.120600  0.297397
75       0.171331  0.349414  0.614331  0.336249  0.160042 -0.343626
...           ...       ...       ...       ...       ...       ...
9999950  0.346824  0.395797  0.993594  0.015392  0.520479 -0.043515
9999954  0.218156  0.017120  0.563860  0.097162  0.324333  0.219307
9999964  0.122860  0.021213  0.822314  0.434304  0.752284  0.423784
9999978  0.418369  0.224771  0.970716  0.395113  0.536504  0.398797
9999993  0.300432  0.165737  0.541427  0.843429  0.422023  0.350267

[998871 rows x 6 columns]

In [ ]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)] #조건으로 사용

A         B         C         D         E         R
18       0.041356  0.100198  0.276245  0.394440  0.882333  0.026671
20       0.217123  0.477318  0.967689  0.242053  0.213274 -0.224509
24       0.495072  0.140023  0.031527  0.244819  0.197128 -3.897975
30       0.032821  0.358893  0.380760  0.818501  0.406686 -0.576875
32       0.195088  0.357181  0.201610  0.426953  0.975694 -1.159978
...           ...       ...       ...       ...       ...       ...
9999981  0.332362  0.063484  0.099762  0.721682  0.810340  0.280811
9999984  0.236359  0.117069  0.422315  0.881178  0.246078  0.175990
9999985  0.436645  0.436728  0.887461  0.615426  0.547837  0.281689
9999993  0.300432  0.165737  0.541427  0.843429  0.422023  0.350267
9999995  0.226616  0.477112  0.191477  0.531367  0.109802 -2.206779

[2497448 rows x 6 columns]

In [ ]:
df.query('A < @col_mean & B < @col_mean')

A         B         C         D         E         R
18       0.041356  0.100198  0.276245  0.394440  0.882333  0.026671
20       0.217123  0.477318  0.967689  0.242053  0.213274 -0.224509
24       0.495072  0.140023  0.031527  0.244819  0.197128 -3.897975
30       0.032821  0.358893  0.380760  0.818501  0.406686 -0.576875
32       0.195088  0.357181  0.201610  0.426953  0.975694 -1.159978
...           ...       ...       ...       ...       ...       ...
9999981  0.332362  0.063484  0.099762  0.721682  0.810340  0.280811
9999984  0.236359  0.117069  0.422315  0.881178  0.246078  0.175990
9999985  0.436645  0.436728  0.887461  0.615426  0.547837  0.281689
9999993  0.300432  0.165737  0.541427  0.843429  0.422023  0.350267
9999995  0.226616  0.477112  0.191477  0.531367  0.109802 -2.206779

[2497448 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [ ]:
s1 = pd.Series(['a', 'b'], index=[1, 2])
s2 = pd.Series(['c', 'd'], index=[3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [ ]:
def create_df(cols, idx):
  data =  {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
  return pd.DataFrame(data, idx)
###


In [ ]:
df1 = create_df('AB', [1, 2])
df1

A   B
1  a1  b1
2  a2  b2

In [ ]:
df2 = create_df('AB', [3, 4])
df2

A   B
3  a3  b3
4  a4  b4

In [ ]:
pd.concat([df1, df2])

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [ ]:
df3 = create_df('AB', [0, 1])
df3

A   B
0  a0  b0
1  a1  b1

In [ ]:
df4 = create_df('CD', [0, 1])
df4

C   D
0  c0  d0
1  c1  d1

In [ ]:
pd.concat([df3, df4])

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [ ]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [ ]:
pd.concat([df1, df3])

A   B
1  a1  b1
2  a2  b2
0  a0  b0
1  a1  b1

In [ ]:
pd.concat([df3, df4], verify_integrity=True) #에러발생하는 것이 정상, 결합하지 말라는 이야기, 왜 Index가 중복이 생기기 때문

ValueError: ignored

In [ ]:
pd.concat([df1, df3], ignore_index=True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [ ]:
pd.concat([df1, df3], keys=['X', 'Y']) #멀티인덱스 구조처럼 X, Y가 추가됨

A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [ ]:
df5 = create_df('ABC', [1, 2])
df6 = create_df('BCD', [3, 4])
pd.concat([df5, df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [ ]:
pd.concat([df5, df6], join='inner') #조인이 되는 부분만, 둘다 존재하는 부분만 조인함

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [ ]:
df5.append(df6)

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

### 병합과 조인

In [ ]:
df1 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유신'],
                  '학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [ ]:
df2 = pd.DataFrame({'학생':['홍길동', '이순신', '임꺽정', '김유신'],
                    '입학년도': [2012, 2016, 2019, 2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [ ]:
df3 = pd.merge(df1, df2)
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [ ]:
df4 = pd.DataFrame({'학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과'],
                    '학과장': ['황희', '장영실', '안창호', '정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [ ]:
pd.merge(df3, df4)


학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df5 = pd.DataFrame({'학과': ['경영학과', '교육학과', '교육학과',  '컴퓨터학과', '컴퓨터학과', '통계학과'],
                    '과목': ['경영학개론', '교육학개론', '상담심리', '프로그래밍', '운영체제', '확률론']})
df5

학과     과목
0   경영학과  경영학개론
1   교육학과  교육학개론
2   교육학과   상담심리
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [ ]:
pd.merge(df1, df5)

학생     학과     과목
0  홍길동   경영학과  경영학개론
1  이순신   교육학과  교육학개론
2  이순신   교육학과   상담심리
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [ ]:
pd.merge(df1, df2, on='학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [ ]:
df6 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '성적': ['A', 'A+', 'B', 'A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [ ]:
pd.merge(df1, df6, left_on='학생', right_on = '이름')

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [ ]:
pd.merge(df1, df6, left_on='학생', right_on = '이름').drop("이름", axis = 1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [ ]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [ ]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [ ]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [ ]:
pd.merge(mdf1, mdf2, left_index=True, right_index=True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [ ]:
mdf1.join(mdf2)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [ ]:
pd.merge(mdf1, df6, left_index=True, right_on='이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [ ]:
df7 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정'],
                    '주문음식': ['햄버거', '피자', '짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [ ]:
df8 = pd.DataFrame({'이름': ['홍길동', '이순신', '김유신'],
                    '주문음료': ['콜라', '사이다', '커피']})
df8

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [ ]:
pd.merge(df7, df8) #둘다 이름이 있는 경우만 출력됨

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [ ]:
pd.merge(df7, df8, how='inner') #default기 inner

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [ ]:
pd.merge(df7, df8, how='outer')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN
3  김유신  NaN   커피

In [ ]:
pd.merge(df7, df8, how='left') #df7에 있는 것만 기준으로

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN

In [ ]:
pd.merge(df7, df8, how='right') #df8에 있는 것만 기준으로

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  김유신  NaN   커피

In [ ]:
df9 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '순위': [3, 2, 4, 1]})
df9

이름  순위
0  홍길동   3
1  이순신   2
2  임꺽정   4
3  김유신   1

In [ ]:
df10 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '순위': [4, 1, 3, 2]})
df10

이름  순위
0  홍길동   4
1  이순신   1
2  임꺽정   3
3  김유신   2

In [ ]:
pd.merge(df9, df10, on='이름')

이름  순위_x  순위_y
0  홍길동     3     4
1  이순신     2     1
2  임꺽정     4     3
3  김유신     1     2

In [ ]:
pd.merge(df9, df10, on='이름', suffixes=['_인기', '_성적'])

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      2      1
2  임꺽정      4      3
3  김유신      1      2

## 데이터 집계와 그룹 연산
|집계|설명|
|---|---|
|count| 전체 개수|
|head, tail| 앞의 항목 일부 반환, 뒤의 항목 일부 반환|
|describe|Series, DataFrame의 각 컬럼에 대한 요약 통계|
|min, max|최소값, 최대값|
|cummin, cummax| 누적 최소값, 누적 최대값|
|idxmin, idxmax| 최소값과 최대값의 색인값|
|mean, median|평균값, 중앙값|
|std, var|표준편자(Standard Deviation), 분산(Variance)|
|skew|왜도(skewnes)값 계산|
|kurt|첨도(kurtosis)값 계산|
|mad|절대 평균 편자(Mean Absolute Deviation)|
|sum, cumsum|전체 항목 합, 누적합|
|prod, cumprod|전체 항목 곱, 누적곱|
|quantile|0부터 1까지의 분위수 게산|
|diff|1차 산술차 계산|
|pct_change|펴센트 변화율 계산|
|corr, cov|상관관계, 공분산 계산|

#### 집계 연산(Aggregation)


In [ ]:
df = pd.DataFrame([[1, 1.2, np.nan],
                   [2.4, 5.5, 4.2],
                   [np.nan, np.nan, np.nan],
                   [0.44, -3.1, -4.1]],
                   index=[1, 2, 3, 4],
                   columns=['A', 'B', 'C'])
df

A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [ ]:
df.head(2)

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [ ]:
df.tail(2)

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1

In [ ]:
df.describe() #요약된 통계값 표시

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  0.050000
std    1.009554  4.30  5.868986
min    0.440000 -3.10 -4.100000
25%    0.720000 -0.95 -2.025000
50%    1.000000  1.20  0.050000
75%    1.700000  3.35  2.125000
max    2.400000  5.50  4.200000

In [ ]:
print(df, "\n")
print(np.argmin(df), "\n")
print(np.argmax(df), "\n")

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1 

2 

2 



In [ ]:
print(df, "\n")
print(df.idxmin(),"\n")
print(df.idxmax(), "\n")

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1 

A    4
B    4
C    4
dtype: int64 

A    2
B    2
C    2
dtype: int64 



In [ ]:
print(df, "\n")
print(df.std(), "\n")
print(df.var(), "\n")

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1 

A    1.009554
B    4.300000
C    5.868986
dtype: float64 

A     1.0192
B    18.4900
C    34.4450
dtype: float64 



In [ ]:
print(df, "\n")
print(df.skew(), "\n")
print(df.kurt(), "\n")

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1 

A    1.15207
B    0.00000
C        NaN
dtype: float64 

A   NaN
B   NaN
C   NaN
dtype: float64 



In [ ]:
print(df, "\n")
print(df.sum(), "\n")
print(df.cumsum(), "\n")

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1 

A    3.84
B    3.60
C    0.10
dtype: float64 

      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  0.1 



In [ ]:
print(df, "\n")
print(df.prod(), "\n")
print(df.cumprod(), "\n")

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1 -4.1 

A     1.056
B   -20.460
C   -17.220
dtype: float64 

       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46 -17.22 



In [ ]:
df.diff()

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [ ]:
df.quantile()

A    1.00
B    1.20
C    0.05
Name: 0.5, dtype: float64

In [ ]:
df.pct_change()

A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -1.97619

In [ ]:
df.corr()

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [ ]:
df.corrwith(df.B) #B값을 기준으로 corrilation 상태를 보겠다.

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [ ]:
df.cov()

A       B       C
A  1.0192   4.214   8.134
B  4.2140  18.490  35.690
C  8.1340  35.690  34.445

In [ ]:
df['B'].unique()

array([ 1.2,  5.5,  nan, -3.1])

In [ ]:
df['A'].value_counts()

0.44    1
2.40    1
1.00    1
Name: A, dtype: int64

### GroupBy 연산

In [5]:
df = pd.DataFrame({'c1': ['a', 'a', 'b', 'b', 'c', 'd', 'b'],
                   'c2': ['A', 'B', 'B', 'A', 'D', 'C', 'C'],
                   'c3': np.random.randint(7),
                   'c4': np.random.random(7)})
df

c1 c2  c3        c4
0  a  A   4  0.662315
1  a  B   4  0.121753
2  b  B   4  0.524932
3  b  A   4  0.569011
4  c  D   4  0.409321
5  d  C   4  0.040779
6  b  C   4  0.106784

In [6]:
df.dtypes

c1     object
c2     object
c3      int64
c4    float64
dtype: object

In [7]:
df['c3'].groupby(df['c1']).mean()

c1
a    4
b    4
c    4
d    4
Name: c3, dtype: int64

In [8]:
df['c4'].groupby(df['c2']).std()

c2
A    0.065976
B    0.285090
C    0.046672
D         NaN
Name: c4, dtype: float64

In [9]:
df['c4'].groupby([df['c1'], df['c2']]).mean() #Series 형태

c1  c2
a   A     0.662315
    B     0.121753
b   A     0.569011
    B     0.524932
    C     0.106784
c   D     0.409321
d   C     0.040779
Name: c4, dtype: float64

In [10]:
df['c4'].groupby([df['c1'], df['c2']]).mean().unstack() #DataFrame형태

c2         A         B         C         D
c1                                        
a   0.662315  0.121753       NaN       NaN
b   0.569011  0.524932  0.106784       NaN
c        NaN       NaN       NaN  0.409321
d        NaN       NaN  0.040779       NaN

In [11]:
df.groupby('c1').mean() #전체를 다 할 때

c3        c4
c1              
a    4  0.392034
b    4  0.400242
c    4  0.409321
d    4  0.040779

In [12]:
df.groupby(['c1', 'c2']).mean()

c3        c4
c1 c2              
a  A    4  0.662315
   B    4  0.121753
b  A    4  0.569011
   B    4  0.524932
   C    4  0.106784
c  D    4  0.409321
d  C    4  0.040779

In [13]:
df.groupby(['c1', 'c2']).size()

c1  c2
a   A     1
    B     1
b   A     1
    B     1
    C     1
c   D     1
d   C     1
dtype: int64

In [14]:
for c1, group in df.groupby('c1'):
  print(c1)
  print(group)
###for

a
  c1 c2  c3        c4
0  a  A   4  0.662315
1  a  B   4  0.121753
b
  c1 c2  c3        c4
2  b  B   4  0.524932
3  b  A   4  0.569011
6  b  C   4  0.106784
c
  c1 c2  c3        c4
4  c  D   4  0.409321
d
  c1 c2  c3        c4
5  d  C   4  0.040779


In [15]:
for (c1, c2), group in df.groupby(['c1', 'c2']):
  print((c1, c2))
  print(group)
###for

('a', 'A')
  c1 c2  c3        c4
0  a  A   4  0.662315
('a', 'B')
  c1 c2  c3        c4
1  a  B   4  0.121753
('b', 'A')
  c1 c2  c3        c4
3  b  A   4  0.569011
('b', 'B')
  c1 c2  c3        c4
2  b  B   4  0.524932
('b', 'C')
  c1 c2  c3        c4
6  b  C   4  0.106784
('c', 'D')
  c1 c2  c3        c4
4  c  D   4  0.409321
('d', 'C')
  c1 c2  c3        c4
5  d  C   4  0.040779


In [16]:
df.groupby(['c1', 'c2'])[['c4']].mean() #c1, c2를 기준으로하고, c4에 대한 mean값만 출력

c4
c1 c2          
a  A   0.662315
   B   0.121753
b  A   0.569011
   B   0.524932
   C   0.106784
c  D   0.409321
d  C   0.040779

In [20]:
df.groupby('c1')['c3'].quantile()

c1
a    4.0
b    4.0
c    4.0
d    4.0
Name: c3, dtype: float64

In [21]:
df.groupby('c1')['c3'].count()

c1
a    2
b    3
c    1
d    1
Name: c3, dtype: int64

In [22]:
df.groupby('c1')['c4'].median()

c1
a    0.392034
b    0.524932
c    0.409321
d    0.040779
Name: c4, dtype: float64

In [23]:
df.groupby('c1')['c4'].std()

c1
a    0.382235
b    0.255096
c         NaN
d         NaN
Name: c4, dtype: float64

In [ ]:
df.groupby('c1')['c4'].std()

In [24]:
df.groupby(['c1', 'c2'])['c4'].agg(['mean', 'min', 'max'])

mean       min       max
c1 c2                              
a  A   0.662315  0.662315  0.662315
   B   0.121753  0.121753  0.121753
b  A   0.569011  0.569011  0.569011
   B   0.524932  0.524932  0.524932
   C   0.106784  0.106784  0.106784
c  D   0.409321  0.409321  0.409321
d  C   0.040779  0.040779  0.040779

In [28]:
df.groupby(['c1', 'c2'], as_index=False)['c4'].mean() #index가 보임

c1 c2        c4
0  a  A  0.662315
1  a  B  0.121753
2  b  A  0.569011
3  b  B  0.524932
4  b  C  0.106784
5  c  D  0.409321
6  d  C  0.040779

In [32]:
df.groupby(['c1', 'c2'], group_keys=False)['c4'].mean()

c1  c2
a   A     0.662315
    B     0.121753
b   A     0.569011
    B     0.524932
    C     0.106784
c   D     0.409321
d   C     0.040779
Name: c4, dtype: float64

In [40]:
def topn(df, n=3, column='c1'): #내가 원하는 집계함수 만들어서 사용도 가능
  return df.sort_values(by=column)[-n:]
###def  

In [41]:
topn(df, n=5)

c1 c2  c3        c4
2  b  B   4  0.524932
3  b  A   4  0.569011
6  b  C   4  0.106784
4  c  D   4  0.409321
5  d  C   4  0.040779

In [42]:
df.groupby('c1').apply(topn) #만들어진 집계함수를 적용하도록

c1 c2  c3        c4
c1                      
a  0  a  A   4  0.662315
   1  a  B   4  0.121753
b  2  b  B   4  0.524932
   3  b  A   4  0.569011
   6  b  C   4  0.106784
c  4  c  D   4  0.409321
d  5  d  C   4  0.040779

### 피벗 테이블(Pivot Table)
|함수|설명|
|---|---|
|values|집계하려는 컬럼 이름 혹은 이름의 리스트, 기본적으로 모든 숫자 컬럼 집계|
|index|피벗테이블의 로우를 그룹으로 묶을 컬럼 이름이나 그룹 키|
|columns|피벗테이블의 컬럼을 그룹으로 묶을 컬림 이름이나 그룹 키|
|aggfunc|집계 함수나 함수 리스트. 기본값으로 mean이 사용|
|fill_value|결과 테이블에서 누락된 값 대체를 위한 값|
|dropna|True인 경우 모든 항목이 NA인 컬럼은 포함되지 않음|
|margins|부분합이나 총계를 담기 위한 로우/컬럼 추가 여부. 기본값은 False|

In [43]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'])

c3                       c4                              
c2    A    B    C    D         A         B         C         D
c1                                                            
a   4.0  4.0  NaN  NaN  0.662315  0.121753       NaN       NaN
b   4.0  4.0  4.0  NaN  0.569011  0.524932  0.106784       NaN
c   NaN  NaN  NaN  4.0       NaN       NaN       NaN  0.409321
d   NaN  NaN  4.0  NaN       NaN       NaN  0.040779       NaN

In [44]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'],
               margins=True) #끝에 부분합 총계인 "All"이 추가됨

c3                           c4                                        
c2     A    B    C    D All         A         B         C         D       All
c1                                                                           
a    4.0  4.0  NaN  NaN   4  0.662315  0.121753       NaN       NaN  0.392034
b    4.0  4.0  4.0  NaN   4  0.569011  0.524932  0.106784       NaN  0.400242
c    NaN  NaN  NaN  4.0   4       NaN       NaN       NaN  0.409321  0.409321
d    NaN  NaN  4.0  NaN   4       NaN       NaN  0.040779       NaN  0.040779
All  4.0  4.0  4.0  4.0   4  0.615663  0.323342  0.073781  0.409321  0.347842

In [45]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'],
               margins=True,
               aggfunc=sum) #집계함수 지정
 

c3                           c4                                        
c2     A    B    C    D All         A         B         C         D       All
c1                                                                           
a    4.0  4.0  NaN  NaN   8  0.662315  0.121753       NaN       NaN  0.784068
b    4.0  4.0  4.0  NaN  12  0.569011  0.524932  0.106784       NaN  1.200726
c    NaN  NaN  NaN  4.0   4       NaN       NaN       NaN  0.409321  0.409321
d    NaN  NaN  4.0  NaN   4       NaN       NaN  0.040779       NaN  0.040779
All  8.0  8.0  8.0  4.0  28  1.231326  0.646684  0.147563  0.409321  2.434894

In [49]:
df.pivot_table(['c3', 'c4'],
               index=['c1'],
               columns=['c2'],
               margins=True,
               aggfunc=sum,
               fill_value=0) #NaN을 0으로 채움

c3                     c4                                        
c2   A  B  C  D All         A         B         C         D       All
c1                                                                   
a    4  4  0  0   8  0.662315  0.121753  0.000000  0.000000  0.784068
b    4  4  4  0  12  0.569011  0.524932  0.106784  0.000000  1.200726
c    0  0  0  4   4  0.000000  0.000000  0.000000  0.409321  0.409321
d    0  0  4  0   4  0.000000  0.000000  0.040779  0.000000  0.040779
All  8  8  8  4  28  1.231326  0.646684  0.147563  0.409321  2.434894

In [50]:
pd.crosstab(df.c1, df.c2)

c2  A  B  C  D
c1            
a   1  1  0  0
b   1  1  1  0
c   0  0  0  1
d   0  0  1  0

In [52]:
pd.crosstab(df.c1, df.c2, values=df.c3, aggfunc=sum, margins=True) #피벗데이블과 비슷한 기능

c2     A    B    C    D  All
c1                          
a    4.0  4.0  NaN  NaN    8
b    4.0  4.0  4.0  NaN   12
c    NaN  NaN  NaN  4.0    4
d    NaN  NaN  4.0  NaN    4
All  8.0  8.0  8.0  4.0   28

### 범주형(Categorical) 데이터
|메소드|설명|
|---|---|
|add_categories|기존 카테고리에 새로운 카테고리 추가|
|as_ordered|카테고리 순서 지정|
|as_unordered|카테고리 순서 미지정|
|remove_categories|카테고리 제거|
|remove_unused_categories|사용않하는 카테고리 제거|
|rename_categories|카테고리 이름 변경|
|reorder_categories|새로운 카테고리에 순서 지정|
|set_categories|새로운 카테고리로 변경|


In [54]:
s = pd.Series(['c1', 'c2', 'c1', 'c2', 'c1'] * 2)
s

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
dtype: object

In [55]:
pd.unique(s)

array(['c1', 'c2'], dtype=object)

In [56]:
pd.value_counts(s)

c1    6
c2    4
dtype: int64

In [58]:
code = pd.Series([0,1,0,1,0] * 2)
code

0    0
1    1
2    0
3    1
4    0
5    0
6    1
7    0
8    1
9    0
dtype: int64

In [59]:
d = pd.Series(['c1', 'c2'])
d

0    c1
1    c2
dtype: object

In [60]:
d.take(code)

0    c1
1    c2
0    c1
1    c2
0    c1
0    c1
1    c2
0    c1
1    c2
0    c1
dtype: object

In [63]:
df = pd.DataFrame({'id': np.arange(len(s)),
                  'c': s,
                  'v': np.random.randint(1000, 5000, size=len(s))})
df

id   c     v
0   0  c1  4201
1   1  c2  4909
2   2  c1  1644
3   3  c2  2626
4   4  c1  2945
5   5  c1  2044
6   6  c2  3022
7   7  c1  4403
8   8  c2  4868
9   9  c1  3779

In [65]:
c = df['c'].astype('category') #df에 있는 'c'라는 걸럼은 카타고리야
c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [66]:
c.values

['c1', 'c2', 'c1', 'c2', 'c1', 'c1', 'c2', 'c1', 'c2', 'c1']
Categories (2, object): ['c1', 'c2']

In [67]:
c.values.categories

Index(['c1', 'c2'], dtype='object')

In [68]:
c.values.codes

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int8)

In [69]:
df['c'] = c
df.c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [70]:
c = pd.Categorical(['c1', 'c2', 'c1', 'c2'])
c

['c1', 'c2', 'c1', 'c2']
Categories (2, object): ['c1', 'c2']

In [73]:
categories = ['c1', 'c2', 'c3']
codes =[0, 1, 2, 0, 1]
c = pd.Categorical.from_codes(codes=codes, categories=categories)
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [74]:
pd.Categorical.from_codes(codes=codes, categories=categories, ordered=True)

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [76]:
c.as_ordered()

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [77]:
c.codes

array([0, 1, 2, 0, 1], dtype=int8)

In [78]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

In [79]:
c = c.set_categories(['c1', 'c2', 'c3', 'c4', 'c5'])
c.categories

Index(['c1', 'c2', 'c3', 'c4', 'c5'], dtype='object')

In [80]:
c.value_counts()

c1    2
c2    2
c3    1
c4    0
c5    0
dtype: int64

In [81]:
c[c.isin(['c1', 'c3'])]

['c1', 'c3', 'c1']
Categories (5, object): ['c1', 'c2', 'c3', 'c4', 'c5']

In [83]:
c = c.remove_unused_categories() #c4, c5등 사용하지 않는 category 제거

In [85]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

## 문자열 연산

#### 문자열 연산자
* 기존 파이썬의 문자열 연산자를 거의 모두 반영

|함수|설명|
|---|---|
|capitalize()|첫 문자를 대문자로하고, 나머지 문자들 소문자로 하는 문자열 반환|
|caseflod()|모든 대소문자 구분을 제거|
|count(sub, [, start[, end]])|[start, end]범위에서 부분 문자열 sub의 중복되지 앟는 수를 반환|
|find(sub, [, start[, end]])|[start, end]에서 부분 문자열 sub가 문자열의 가장 작은 인덱스를 반환, sub가 발견되지 않는 경우는 -1 반환|
|rfind(sub, [, start[, end]])|[start, end]에서 부분 문자열 sub가 가장 큰 인덱스를 반환, sub가 발견되지 않는 경우는 -1 반환|
|index(sub, [, start[, end]])|find()와 유사하지만 부분 문자열 sub가 없으면 ValueError 발생|
|rindex(sub, [, start[, end]])|rfind()와 유사하지만 부분 문자열 sub가 없으면 ValueError 발생|
|isalnum()||
|isalpha()||
|isdecimal()||
|isdigit()||
|isnumerical()||
|||
|||
|||
|||
|||
|||
|||

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly